name: CI/CD - Deploy to Development

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Build NextJS Application
    runs-on: ubuntu-latest
    environment: Development

    steps:
      # Step 1: Checkout the code
      - name: Checkout development branch
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build -f .docker/Dockerfile \
            --build-arg NEXT_PUBLIC_IPFS_URL=${{ vars.NEXT_PUBLIC_IPFS_URL }} \
            --build-arg NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }} \
            --build-arg NEXT_PUBLIC_CONTRACT_ADDRESS=${{ vars.NEXT_PUBLIC_CONTRACT_ADDRESS }} \
            --build-arg NEXT_PUBLIC_FRONTEND_URL=${{ vars.NEXT_PUBLIC_FRONTEND_URL }} \
          -t ${{ vars.DOCKER_USER }}/${{vars.IMAGE_NAME}}:latest .

      # Step 4: Push the Docker Image to Registry
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ vars.DOCKER_USER }}/${{vars.IMAGE_NAME}}:latest

  deploy:
    name: Deploy to Server with Docker
    runs-on: self-hosted
    environment: Development
    needs: [build]

    steps:
      # Step 1: Deploy using Docker Compose
      - name: Deploy with Docker
        run: |
          cd ~/app/cert-chain-admin
          docker compose pull
          docker compose down
          docker compose up -d